name: Build and test
on:
  workflow_dispatch:
   

jobs:
  runner-job:
    runs-on: ubuntu-latest
   
    steps:
    - uses: actions/checkout@v2

    - name: Install Dependencies
      run: npm install

    - name: Build
      run: npm build

    - name: Unit Test
      run: npm run test
           
    services:
      # Label used to access the service container
      azure-storage:
        # Docker Hub image
        image: mcr.microsoft.com/azure-storage/azurite
        # Docker port mapping
        ports:          
          - 10000:10000
          - 10001:10001
